// <auto-generated />
using System;
using Mardre.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mardre.Migrations
{
    [DbContext(typeof(EngenhariasSenacContext))]
    partial class EngenhariasSenacContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mardre.Models.Categoria", b =>
                {
                    b.Property<int>("CodCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCategoria"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Mardre.Models.MateriaPrima", b =>
                {
                    b.Property<int>("CodMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodMateria"));

                    b.Property<int?>("CodCategoria")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descarte")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("EmissaoCo2")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int?>("EstoqueMax")
                        .HasColumnType("int");

                    b.Property<int?>("EstoqueMin")
                        .HasColumnType("int");

                    b.Property<decimal?>("FatorCo2")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CodMateria");

                    b.HasIndex("CodCategoria");

                    b.ToTable("Materia_Prima");
                });

            modelBuilder.Entity("Mardre.Models.Processamento", b =>
                {
                    b.Property<int>("CodProcessamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodProcessamento"));

                    b.Property<int?>("CodMateria")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("RegistroFotografico")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TempoClassificacao")
                        .HasColumnType("int");

                    b.Property<int?>("TempoLeitura")
                        .HasColumnType("int");

                    b.Property<int?>("TempoPesagem")
                        .HasColumnType("int");

                    b.Property<int?>("TempoRedirecionamento")
                        .HasColumnType("int");

                    b.Property<int?>("TempoTotalProcessamento")
                        .HasColumnType("int");

                    b.HasKey("CodProcessamento");

                    b.HasIndex("CodMateria");

                    b.ToTable("Processamento");
                });

            modelBuilder.Entity("Mardre.Models.MateriaPrima", b =>
                {
                    b.HasOne("Mardre.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CodCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Mardre.Models.Processamento", b =>
                {
                    b.HasOne("Mardre.Models.MateriaPrima", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("CodMateria");

                    b.Navigation("MateriaPrima");
                });
#pragma warning restore 612, 618
        }
    }
}
